#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Configure traefik route for the module

import os
import sys
import json
import agent

data = json.load(sys.stdin)
# Setup default values
host = data["host"]
## Configure set-route
set_route_data = {
    'instance': os.environ['MODULE_ID'],
    'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
    'http2https': True,
    'host': host,
    'lets_encrypt_check': True,
    'lets_encrypt_cleanup': True,
}
if 'lets_encrypt' in data:
    set_route_data['lets_encrypt'] = data['lets_encrypt']

agent.set_route(set_route_data)
