#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

is_collabora=$(cat /dev/stdin | jq -r '.is_collabora')

if  $is_collabora && [[ $COLLABORA_HOST != "" ]]; then
    occ app:install richdocuments
    occ config:app:set richdocuments wopi_url --value=https://$COLLABORA_HOST
    if [[ $TLS_VERIFY_COLLABORA == 'True' ]]; then
        occ config:app:set richdocuments disable_certificate_verification --value=no
    else
        occ config:app:set richdocuments disable_certificate_verification --value=yes
    fi
    occ app:enable richdocuments
fi
