#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# with nextcloud 28 the logreader app is compatible only with `file` log type
# see https://github.com/nextcloud/server/issues/45517
#  Failed to get an iterator for log entries: Logreader application only supports "file" log_type
occ app:disable logreader

# install and configure files high performance backend
occ app:install notify_push
occ app:enable notify_push
occ -n notify_push:setup http://127.0.0.1/push

# Suppress error when notify push versions do not match, see https://github.com/NethServer/dev/issues/7450
exit 0