#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import subprocess
import sys

def occget(args):
    cmd = ['podman', 'exec', '--user', 'www-data', 'nextcloud-app', 'php', './occ']
    p = subprocess.run(cmd + args, capture_output=True)
    return (p.stdout.decode().rstrip())

with open('config.json', 'r') as cf:
    config = json.loads(cf.read())

# Exit if internal smarthost is already set
if "internal_smarthost" in config:
    sys.exit(0)

smarthost = agent.read_envfile("smarthost.env")

# Get the smtphost via occ
smtphost = occget(["config:system:get","mail_smtphost"])

# Get the smarthost
if 'SMTP_HOST' in smarthost:
    smtpsmarthost=smarthost['SMTP_HOST']
else:
    smtpsmarthost=""

# Compare occ with smarthost settings and set the internal_smarthost variable accordingly
if smtphost == smtpsmarthost:
    config["internal_smarthost"] = False
else:
    config["internal_smarthost"] = True

# Write config.json
with open('config.json', 'w') as cfp:
    cfp.write(json.dumps(config))
