#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import subprocess

def occget(args):
    cmd = ['podman', 'exec', '--user', 'www-data', 'nextcloud-app', 'php', './occ']
    p = subprocess.run(cmd + args, capture_output=True)
    return (p.stdout.decode()[:-1])

smarthost = agent.read_envfile("smarthost.env")
configenv = agent.read_envfile("config.env")

with open('config.json', 'r') as cf:
    configjson = json.loads(cf.read())

# Exit if internal smarthost is already set
if 'INTERNAL_SMARTHOST' in configenv:
    sys.exit(0)

# Get the smtphost via occ
smtphost = occget(["config:system:get","mail_smtphost"])

# Get the smarthost
if 'SMTP_HOST' in smarthost:
    smtpsmarthost=smarthost['SMTP_HOST']
else:
    smtpsmarthost=""

# Compare occ with smarthost settings and set the internal_smarthost variable accordingly
if smtphost == smtpsmarthost:
    configenv['INTERNAL_SMARTHOST']='False'
    configjson["internal_smarthost"] = False
    agent.write_envfile('config.env', configenv)
else:
    configenv['INTERNAL_SMARTHOST']='True'
    configjson["internal_smarthost"] = True
    agent.write_envfile('config.env', configenv)

# Write config.json
with open('config.json', 'w') as cfp:
    cfp.write(json.dumps(configjson))
