#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

systemctl --user try-restart nextcloud.service nextcloud-redis.service nextcloud-db.service nextcloud-app.service nextcloud-nginx.service nextcloud-notify_push.service
sleep 5 # prevent fast race with entrypoint.sh
podman exec nextcloud-app flock nextcloud-init-sync.lock true || true # wait occ upgrade
