#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Wait for the Nextcloud Docker image entrypoint to complete initialization or upgrade.
# The entrypoint holds nextcloud-init-sync.lock while running occ upgrade.
# Acquiring the lock means the entrypoint has finished.
#

sleep 5 # prevent fast race with entrypoint.sh
podman exec nextcloud-app flock nextcloud-init-sync.lock true || true
